---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build_and_publish_image
  image: plugins/docker
  settings:
    repo: jmreicha/sentry
    tags: 9.1
    dockerfile: 9.1/Dockerfile
    context: 9.1
    username:
      from_secret: DH_USER
    password:
      from_secret: DH_PASS
